import{a as M,S as v,i as s}from"./assets/vendor-mdVVRe9K.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="45969466-58730abf31a7490a9e4f6988e",E="https://pixabay.com/api/";async function p(t,n=1,o=15){try{return(await M.get(E,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:o}})).data}catch(i){throw console.error("Error fetching images:",i),i}}let d=null;function y(t,n){const o=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:a,views:O,comments:I,downloads:S})=>`
    <li class="gallery-item">
            <a href="${e}" >
                <img class="gallery-img" src="${i}" alt="${r}" loading="lazy" />
                <div class="info">
                    <p><b>Likes</b> ${a}</p>
                    <p><b>Views</b> ${O}</p>
                    <p><b>Comments</b> ${I}</p>
                    <p><b>Downloads</b> ${S}</p>
                </div>
            </a>
        </li>
  `).join("");n.insertAdjacentHTML("beforeend",o),d?d.refresh():d=new v(".gallery a")}function q(t){t.innerHTML=""}const g=document.querySelector("#search-form"),u=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more");let l=1,f="",c=0;g.addEventListener("submit",R);m.addEventListener("click",$);async function R(t){t.preventDefault();const n=t.target.elements.searchQuery.value.trim();if(n===""){s.warning({timeout:1e3,close:!0,position:"topRight",transitionIn:"fadeIn",transitionOut:"fadeOut",displayMode:2,message:"Please enter a search query!"});return}f=n,l=1,c=0,q(u),B(),L(),b();try{const o=await p(f,l);if(c=o.totalHits,o.hits.length===0){s.error({timeout:1e3,close:!0,position:"topRight",transitionIn:"fadeIn",transitionOut:"fadeOut",displayMode:2,message:"Sorry, there are no images matching your search query. Please, try again!"});return}y(o.hits,u),c>15&&H()}catch(o){s.error({timeout:1e3,close:!0,position:"topRight",transitionIn:"fadeIn",transitionOut:"fadeOut",displayMode:2,message:"Something went wrong. Please try again later."}),console.error("Error fetching images:",o)}finally{w()}}async function $(){l+=1,b();try{const t=await p(f,l);y(t.hits,u),x(),l*15>=c&&(L(),s.info({timeout:5e3,close:!0,position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(t){s.error({timeout:1e4,close:!0,position:"topRight",transitionIn:"fadeIn",transitionOut:"fadeOut",displayMode:2,message:"Something went wrong. Please try again later."}),console.error("Error fetching more images:",t)}finally{w()}}function b(){h.style.display="block"}function w(){h.style.display="none"}function B(){g.elements.searchQuery.value=""}function H(){m.style.display="block"}function L(){m.style.display="none"}function x(){const{height:t}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
